default_language_version:
  python: python3
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.16.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
        additional_dependencies:
          [
            "overrides",
            "python-dotenv",
          ]
      - id: pylint
        args: ["tests", "--rcfile=.pylintrc.tests"]
        additional_dependencies:
          [
            "overrides",
            "python-dotenv",
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy argparsenv
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: doctests
        name: doctests
        entry: pytest --doctest-modules argparsenv
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: unittests
        name: unittests
        entry: pytest -v
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: coverage_report
        name: coverage report
        entry: pytest --cov-report html --cov=.
        language: python
        additional_dependencies:
          [
            "pytest-cov",
            "python-dotenv",
            "overrides"
          ]
        pass_filenames: false
        always_run: true
