[project]
name = "argparsenv"
version = "1.0.11"
requires-python = ">=3.11,<4.0"
description = "Extends python's argparser with environment variables"
license = "MIT"
readme = "README.md"
dependencies = [
    "python-dotenv>=1.0.1",
    "overrides>=7.7.0",
]

[dependency-groups]
dev = [
    "black==26.3.1",
    "pytest-cov==7",
    "mypy==1.10",
    "pdoc==14.5.1",
    "bandit==1.7",
    "pylint==4"
]

[project.urls]
Homepage = "https://github.com/snaeil/argparsenv"
Repository = "https://github.com/snaeil/argparsenv"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
