name: Checks and tests

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies and tools
        run: |
          uv sync --all-groups
      - name: Run format check with black
        run: |
          uv run black --check .
      - name: Run linter with pylint
        run: |
          uv run pylint --rcfile=.pylintrc */**.py
          uv run pylint tests --rcfile=.pylintrc.tests
      - name: Run type checks with mypy
        run: |
          uv run mypy argparsenv
      - name: Run unit tests with pytest
        run: |
          uv run pytest -v
      - name: Run doctests with pytest
        run: |
          uv run pytest --doctest-modules
      - name: Run audit
        run: |
          uv audit
