name: Create Release


on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # TODO: allow only semver tags in a strict way

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
      # TODO: use changelog for body
      #   bodyFile: "body.md"
